CREATE TABLE RENDEZ_VOUS 
   (	"ID_RENDEZ_VOUS" NUMBER(*,0), 
	"ID_EMPLOYE" NUMBER(*,0), 
	"NUM_SALLE" NUMBER(*,0), 
	"ID_PATIENT" NUMBER(*,0), 
	"DATE" DATE, 
	"HEURE" VARCHAR2(20 BYTE)
   );

CREATE TABLE EMPLOYES
   (	"ID_EMPLOYE" NUMBER(*,0), 
	"CIN" NUMBER(8,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"HEURE_DE_TRAVAIL" DATE, 
	"MDP" VARCHAR2(10 BYTE)
   );

CREATE TABLE EQUIPEMENTS 
   (	"REFERENCES" VARCHAR2(10 BYTE), 
	"QUANTITE" NUMBER(*,0), 
	"PRIX" NUMBER(*,0)
   );

CREATE TABLE PATIENTS 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(30 BYTE), 
	"NUM_TEL" VARCHAR2(8 BYTE), 
	"DATE_NES" DATE, 
	"HISTORIQUE_MED" VARCHAR2(100 BYTE), 
	"DIAGNOSTIQUE" VARCHAR2(100 BYTE)
   );

CREATE TABLE SALLES 
   (	"NUM_SALLE" NUMBER(*,0), 
	"TYPE" VARCHAR2(20 BYTE), 
	"CAPACITE" NUMBER(*,0)
   );

CREATE TABLE THERAPIES 
   (	"ID_THERAPIE" NUMBER(*,0), 
	"TYPE" VARCHAR2(20 BYTE), 
	"ACTIVITE" VARCHAR2(20 BYTE)
   );

CREATE UNIQUE INDEX PK_PATIENT ON "PATIENTS" ("ID");
CREATE UNIQUE INDEX UK_PATIENT ON "PATIENTS" ("NOM", "PRENOM", "DATE_NES");

ALTER TABLE "RENDEZ_VOUS" MODIFY ("HEURE" NOT NULL ENABLE);
ALTER TABLE "RENDEZ_VOUS" MODIFY ("DATE" NOT NULL ENABLE);
ALTER TABLE "RENDEZ_VOUS" MODIFY ("ID_PATIENT" NOT NULL ENABLE);
ALTER TABLE "RENDEZ_VOUS" MODIFY ("NUM_SALLE" NOT NULL ENABLE);
ALTER TABLE "RENDEZ_VOUS" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
ALTER TABLE "RENDEZ_VOUS" MODIFY ("ID_RENDEZ_VOUS" NOT NULL ENABLE);

ALTER TABLE "EMPLOYES" MODIFY ("MDP" NOT NULL ENABLE);
ALTER TABLE "EMPLOYES" MODIFY ("HEURE_DE_TRAVAIL" NOT NULL ENABLE);
ALTER TABLE "EMPLOYES" MODIFY ("PRENOM" NOT NULL ENABLE);
ALTER TABLE "EMPLOYES" MODIFY ("NOM" NOT NULL ENABLE);
ALTER TABLE "EMPLOYES" MODIFY ("CIN" NOT NULL ENABLE);
ALTER TABLE "EMPLOYES" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);

ALTER TABLE "EQUIPEMENTS" MODIFY ("PRIX" NOT NULL ENABLE);
ALTER TABLE "EQUIPEMENTS" MODIFY ("QUANTITE" NOT NULL ENABLE);
ALTER TABLE "EQUIPEMENTS" MODIFY ("REFERENCES" NOT NULL ENABLE);

ALTER TABLE "PATIENTS" ADD CONSTRAINT "CK_PATIENT2" CHECK (LENGTH(PRENOM)>2) ENABLE;
ALTER TABLE "PATIENTS" ADD CONSTRAINT "CK_PATIENT" CHECK (LENGTH(NOM)>2) ENABLE;
ALTER TABLE "PATIENTS" ADD CONSTRAINT "UK_PATIENT" UNIQUE ("NOM", "PRENOM", "DATE_NES");
ALTER TABLE "PATIENTS" ADD CONSTRAINT "PK_PATIENT" PRIMARY KEY ("ID");
ALTER TABLE "PATIENTS" MODIFY ("DIAGNOSTIQUE" NOT NULL ENABLE);
ALTER TABLE "PATIENTS" MODIFY ("DATE_NES" NOT NULL ENABLE);
ALTER TABLE "PATIENTS" MODIFY ("NUM_TEL" NOT NULL ENABLE);
ALTER TABLE "PATIENTS" MODIFY ("ADRESSE" NOT NULL ENABLE);
ALTER TABLE "PATIENTS" MODIFY ("PRENOM" NOT NULL ENABLE);
ALTER TABLE "PATIENTS" MODIFY ("NOM" NOT NULL ENABLE);
ALTER TABLE "PATIENTS" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "SALLES" MODIFY ("CAPACITE" NOT NULL ENABLE);
ALTER TABLE "SALLES" MODIFY ("TYPE" NOT NULL ENABLE);
ALTER TABLE "SALLES" MODIFY ("NUM_SALLE" NOT NULL ENABLE);

ALTER TABLE "THERAPIES" MODIFY ("ACTIVITE" VARCHAR2(20) NOT NULL);
ALTER TABLE "THERAPIES" MODIFY ("TYPE" VARCHAR2(20) NOT NULL);
ALTER TABLE "THERAPIES" MODIFY ("ID_THERAPIE" NUMBER(10) NOT NULL);